---
- name:  Retrieve system info
  hosts: all
  gather_facts: false
  tasks:
  
    - win_shell: Get-CimInstance Win32_OperatingSystem | Select-Object  Caption, InstallDate, ServicePackMajorVersion, OSArchitecture, BootDevice,  BuildNumber, CSName | FL
