---
- name: Create an Active Directory User Account
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Create the user account
    win_domain_user:
      username: '{{ name }}'
      name: '{{ name }}'
      firstname: '{{ firstname }}'
      surname: '{{ surname }}'
      password: '{{ password }}'
      path: '{{ ou }}'
      email: '{{ email }}'
      upn: '{{ email }}'
      company: '{{ company }}'
      update_password: on_create
      attributes:
        displayname: '{{ displayname }}'
        department: '{{ department }}'
      enabled: '{{ status }}'
      state: present 
