---
- name:  Run command on Windows Remote Host
  hosts: '{{ target }}'
  gather_facts: false
  tasks:
  
    - name: Build Project Professional 2016 x86 APP-V package
      win_command: C:\Temp\setup.exe /packager C:\Temp\Office2016ProjectPro-x86.xml C:\Temp\ProjectPro
      register: setup_out
      
      - name: Build Visio Professional 2016 x86 APP-V package
      win_command: C:\Temp\setup.exe /packager C:\Temp\Office2016VisioPro-x86.xml C:\Temp\VisioPro
      register: setup_out
        
