---
- hosts: all
  gather_facts: false
  connection: local
  
  vars:
    guests:
      - "192.168.0.11"
      - "192.168.0.13"
  
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - vmware_guest:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      esxi_hostname: '{{ item.1 }}'
      datacenter: 'Datacenter'
      folder: Hosts
      name: "{{ inventory_hostname + '-' }}{{ 100 | random }}"
      state: present
      guest_id: windows9_64guest
      template: Windows-10-1803-x64
      wait_for_ip_address: no
    loop: "{{ guests }}"
