---
- hosts: all
  gather_facts: false
  connection: local
    
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - vmware_guest:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      esxi_hostname: '{{ esx_host }}'
      datacenter: 'Datacenter'
      folder: Hosts
      name: '{{ item }}'
      state: present
      guest_id: windows9_64guest
      template: Windows-10-1803-x64
      wait_for_ip_address: no
    with_sequence: start=1 end='{{ amount }}' format="{{ inventory_hostname + '_' }}{{ 999 |random(seed=inventory_hostname) }}"
