---

- hosts: '{{ domain_server }}'
  gather_facts: false
  connection: local
  
  tasks:
  - name: Create Windows AD User Account
    win_domain_user:
      name: '{{ samaccountname }}'
      firstname: '{{ givenName }}'
      surname: '{{ lastName }}'
      password: '{{ password }}'
      path: '{{ OU_DN }}'
      state: present
      domain_username: '{{ domain_account }}'
      domain_password: '{{ domain_account_password }}'
      domain_server: '{{ domain_server }}'
