---
- hosts: all
  gather_facts: false
  connection: local
  
  vars:
    guests:
      - esxi_hostname: 192.168.0.11
        hosts: 
          - name: DESKTOP-01
            name: DESKTOP-02
            name: DESKTOP-03
            name: DESKTOP-04
            name: DESKTOP-05
            name: DESKTOP-06
      - esxi_hostname: 192.168.0.13
        hosts: 
          - name: DESKTOP-07
            name: DESKTOP-08
            name: DESKTOP-09
            name: DESKTOP-10
 
  
  tasks:
  # get date
  - set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"
  # Create a VM from a template
  - vmware_guest:
      hostname: '{{ vsphere_host }}'
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      esxi_hostname: '{{ item.0.esxi_hostname }}'
      datacenter: 'Datacenter'
      folder: Hosts
      name: '{{ item.1.name }}'
      state: present
      guest_id: windows9_64guest
      template: Windows-10-1803-x64
      wait_for_ip_address: yes
    with_subelements:
      - '{{ guests }}'
      - hosts
