---

- hosts: '{{ domain_server }}'
  gather_facts: false
  connection: local
  
  tasks:
  - name: Create Windows AD User Account
    win_domain_user:
      name: '{{ uname }}'
      firstname: '{{ ufirstname }}'
      surname: '{{ usurname }}'  
      password: '{{ upassword }}'
      path: '{{ upath }}'
      state: present
      attributes:
        displayname: '{{ udisplayname }}'
      domain_username: '{{ udomain_username }}'
      domain_password: '{{ udomain_password }}'
