---

- hosts: '{{ domain_server }}'
  gather_facts: false
  connection: local
  
  tasks:
  - name: Create Windows AD User Account
    win_domain_user:
      name: '{{ name }}'
      firstname: '{{ firstname }}'
      surname: '{{ surname }}'  
      password: '{{ password }}'
      state: present      
      city: '{{ city }}'
      company: '{{ company }}'
      country: '{{ country }}'
      description: '{{ description }}'
      email: '{{ email }}'
      path: '{{ path }}'
      postal_code: '{{ postal_code }}'
      state_province: '{{ state_province }}'
      street: '{{ street }}'
      upn: '{{ upn }}'
      attributes:
        displayname: '{{ displayname }}'
        telephoneNumber: '{{ telephoneNumber }}'
        mobile: '{{ mobile }}'
        department: '{{ department }}'
      domain_username: '{{ domain_username }}'
      domain_password: '{{ domain_password }}'       

