---
- name:  Retrieve system info
  hosts: all
  gather_facts: false
  tasks:
  
    - win_shell: get-wmiobject -class win32_OperatingSystem | Select-Object -Property CSName,ProductType,Caption,Version,OSArchitecture,CSDVersion
