---
- name: Get all nodes from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        force_basic_auth: yes
        return_content: yes
      register: resp_data
      
    - debug: var=resp_data
    
    - name: Print node name
      debug:
        msg: "{{ resp_data.content.node.label }}"  
