---
- name: Get all nodes from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
   # - debug: msg="Node label"
   #   with_items: "{{ result.json.node[1].label }}"
      
    - debug: msg="Result"
    with_items: "{{ result.results | map('from_json') | map(attribute='node') | sum(start=[]) | map(attribute='label') | list }}"
