---
- name: Add node to OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Add the node to the service
      uri:
        url: https://{{ hostname }}/opennms/rest/requisitions/{{ node_requisition }}/nodes
        method: POST
        headers:
          Content-type: application/xml
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 202
        body: |+
          <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
            <node type="A" node-label="{{ node_label }}" foreign-id="{{ node_label }}" building="{{ node_building }}">
              <interface snmp-primary="N" status="1" ip-addr="{{ node_ipv4_address }}" descr="{{ node_description }}">
              </interface>
            </node>
      
    - name: Activate the node
      uri:
        url: https://{{ hostname }}/opennms/rest/requisitions/{{ node_requisition }}/import
        method: PUT
        headers:
          Content-type: application/x-www-form-urlencoded
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 202
      
      
