---
- name: Get all nodes from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
    - name: Iterate JSON
      set_fact:
        app_item: "{{ result.json.node[1].label }}"
      with_items: "{{ result.json.node }}"
      register: app_result
      
    - name: Create Fact List
      set_fact:
         apps: "{{ app_result.results | map(attribute='ansible_facts.app_item') | list }}"
    
    - name:  Print Fact
      debug: var=apps
