---
- name: Get all nodes from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
    - name: Print node label
      var=result.json.node | json_query([?label==" {{ node_to_remove }} "])
      debug:
        msg: "{{ item }}"
        when: 
          loop: "{{ result | json_query('json.node[*].label) == '{{ node_to_remove }}' }}"

