---
- name: Request all active requisitions from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Do the request
      uri:
        url: https://{{ hostname }}/opennms/rest/requisitions/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
    - set_fact:
        req_all: "{{ result.json['model-import'] | map(attribute='foreign-source') | list }}"
    
    - debug: var=req_all
