---
- name: Remove node from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
        
    - name: Get node from openNMS and store in variable
      set_fact:
        label: "{{ result.json.node | map(attribute='label') | list }}"
    
    - debug:
        msg: "Node found: {{ item }}"
      with_items: "{{ label }}"
      when: node_to_remove == item

        
      

