---
- name: Remove node from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
   # - name: Get nodes from openNMS and store attributes label and ID in list
    #  set_fact:
     #   nodes: "{{ result | from_json }}"
      #with_items: "{{ result.json.node | list }}"
    
    - debug: var={{ item }}
      with_dict: "{{ result }}"
    
   # - debug:
    #    var: result
     #   verbosity: 2
        #msg: "Node found {{ item['label'] }} with id {{ item['id'] }}"
      #with_dict: "{{ lookup('dict', result) }}"
      #when: node_to_remove == item['label']

        
      

