---
- name: Get all nodes from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
        
    - name: Jinja list debug, printing out the list as comma seperated.
      set_fact:
        #msg: "{% for each in result.json.node %}{{ each }}{% if not loop.last %},{% endif %}{% endfor %}"
        label_value: "{{ result.json.node | map(attribute='label') | list }}"
    
    - debug:
        msg: "{{ label_value }}"
        when: node_to_remove is in label_value
      

