---
- name: Get all nodes from OpenNMS
  hosts: "{{ HOSTS }}"
  gather_facts: false
  connection: local
  
  tasks:
    - name: request all nodes
      uri:
        url: https://"{{ HOSTNAME }}"/opennms/rest/nodes/
        method: POST
        user: "{{ USERNAME }}"
        password: "{{ PASSWORD }}"
        force_basic_auth: yes
        return_content: true
