---
- name: Get all nodes from OpenNMS
  
  tasks:
    - name: request all nodes
      uri:
        url: https://{{ HOSTNAME }}/opennms/rest/nodes/
        method: POST
        user: {{ USERNAME }}
        password: {{ PASSWORD }}
        force_basic_auth: yes
        return_content: true
