---
- name: Get all nodes from OpenNMS
  hosts: tower.armandit.com
  gather_facts: false
  connection: local
  
  tasks:
    - name: request all nodes
      uri:
        url: https://"{{ hostname }}"/opennms/rest/nodes/
        method: POST
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        force_basic_auth: yes
        return_content: true
