---
- name: Remove node from OpenNMS
  hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
    - name: Request all nodes
      uri:
        url: https://{{ hostname }}/opennms/rest/nodes/
        method: GET
        headers:
          Accept: application/json
        user: "{{ u_username }}"
        password: "{{ u_password }}"
        body_format: json
        force_basic_auth: yes
        return_content: yes
      register: result
      
    - name: Create new variables from json output
      set_fact: {"{{ item.key }}":"{{ item.val }}"}
      with_dict: "{{result.json.node}}"
        
    - name: Get node from openNMS and store in variable
      set_fact:
        item_label: "{{ result.json.node | map(attribute='label') | list }}"
    
    - debug:
        msg: "Node found: {{ label }} with ID {{ ID }}"
      with_items: "{{ item_label }}"
      when: node_to_remove == item

        
      

