---
- name: Check the webservers SSLLabs security rating using their scan plugin
  hosts: localhost
  gather_facts: no
  vars:
    webserver: "{{ websiteaddress }}"
  

  tasks:
  - name:  the role
    command: ansible-galaxy install -r ./roles/requirements.yml
    
  - name: run the SSLLabs scan tool
    command: ssllabs-scan --grade {{ websiteaddress }}
