---
- name: Check the webservers SSLLabs security rating using their scan plugin
  hosts: localhost
  gather_facts: no
  vars:
    webserver: "{{ websiteaddress }}"  

  tasks:
  - name: Import the role
    import_role:
      name: '30.ansible_ssllabs_scan'

  - name: run the SSLLabs scan tool
    command: ssllabs-scan --grade {{ websiteaddress }}
