---
- hosts: all
  gather_facts: false
  connection: local
  
- name: Gather all registered virtual machines
  vmware_vm_facts:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
  register: vmfacts

- debug:
    var: vmfacts.virtual_machines
