---
- name:  Download and install a PFX certificate on a Windows host.
  hosts: '{{ target }}'
  gather_facts: false

  tasks:
  - name: Download certificate
  get_url:
    url: {{ cert-url }}
    dest: C:\temp\certificate.pfx
  
  - name: Import the certificate
    win_certificate_store:
      path: C:\temp\certificate.pfx
      file_type: {{ cert-type }}
      password: {{ cert-password }}
      store_location: {{ cert-storelocation }}
      key_storage: {{ cert-keystorage }}
      state: present
