---

- name: Check Windows host for available updates
  hosts: all

  tasks:
      - block:
          - name: Check for missing updates.
            win_updates: state=searched
            register: update_count
          - name: List missing updates
            debug: var=update_count
