---
- name: Set password for local windows account
  hosts: "{{ vm_hostname }}"
  gather_facts: false
  connection: local
  
  tasks:
    - name: Connect to host and set password required for local Administrator account
      win_command: net user Administrator "{{ pass }}" /passwordreq:yes
  
    - name: Set password for local windows account
      win_user:
        name: "{{ user }}"
        password: "{{ pass }}"
        update_password: always
