---
- name:  Install any SSL certificate on a Windows host
  hosts: '{{ target }}'
  gather_facts: false

  tasks:
  - name: Import certificate be used by IIS
    win_certificate_store:
      path: {{ cert-file }}
      file_type: {{ cert-type }}
      password: {{ cert-password }}
      store_location: {{ cert-storelocation }}
      key_storage: {{ cert-keystorage }}
      state: present
