---
- name: Download and install a PFX certificate on a Windows host.
  hosts: '{{ resourcename }}'
  gather_facts: False
  vars:
    ansible_user: '{{ pmp_accountname }}'
    ansible_password: "{{ lookup('passwordmanagerpro','{{ pmp_resourcename }}', '{{ pmp_accountname }}') }}"

  tasks:
      - block:
          - name: Download certificate and save in Temp
            win_get_url:
              url: '{{ cert_url }}'
              dest: C:\temp\certificate.pfx
          - name: Import the certificate
            win_certificate_store:
              path: C:\temp\certificate.pfx
              file_type: '{{ cert_type }}'
              password: '{{ cert_password }}'
              store_location: '{{ cert_storelocation }}'
              key_storage: '{{ cert_keystorage }}'
              state: present
          - name: Remove the certificate from the Temp folder
            win_file:
              path: C:\temp\certificate.pfx
              state: absent
