---
- name: Add or remove a registry key
  hosts: '{{ resourcename }}'
  gather_facts: False


  tasks:
      - block:
          - name: Adds or removes the key
            win_regedit:
              path: '{{ reg_keypath }}'
              name: '{{ reg_keyname }}'
              data: '{{ reg_keydata }}'
              type: '{{ reg_keytype }}'
              state: '{{reg_keystate }}'
