---
- name: Add or remove a registry key
  hosts: '{{ resourcename }}'
  no_log: True
  gather_facts: False
  vars:
    ansible_user: '{{ pmp_accountname }}'
    ansible_password: "{{ lookup('passwordmanagerpro','{{ pmp_resourcename }}', '{{ pmp_accountname }}') }}"

  tasks:
      - block:
          - name: Adds the key
            win_regedit:
              path: '{{ reg_keypath }}'
            tags:
            - key  
          - name: Adds or removes the keyvalue
            win_regedit:
              path: '{{ reg_keypath }}'
              name: '{{ reg_keyname }}'
              data: '{{ reg_keydata }}'
              type: '{{ reg_keytype }}'
              state: '{{reg_keystate }}'
            tags:
            - keyvalue
